using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BudgetForecast.Model
{
    public class StoreSearchForecastPmModel
    {
        public string SEC { get; set; }
        public string StYr { get; set; }
        public double BUD00 { get; set; }
        public double BUD01 { get; set; }
        public double BUD02 { get; set; }
        public double BUD03 { get; set; }
        public double BUD04 { get; set; }
        public double BUD05 { get; set; }
        public double BUD06 { get; set; }
        public double BUD07 { get; set; }
        public double BUD08 { get; set; }
        public double BUD09 { get; set; }
        public double BUD10 { get; set; }
        public double BUD11 { get; set; }
        public double BUD12 { get; set; }
        public double BUDYTD { get; set; }
        public double ACM_BUD01 { get; set; }
        public double ACM_BUD02 { get; set; }
        public double ACM_BUD03 { get; set; }
        public double ACM_BUD04 { get; set; }
        public double ACM_BUD05 { get; set; }
        public double ACM_BUD06 { get; set; }
        public double ACM_BUD07 { get; set; }
        public double ACM_BUD08 { get; set; }
        public double ACM_BUD09 { get; set; }
        public double ACM_BUD10 { get; set; }
        public double ACM_BUD11 { get; set; }
        public double ACM_BUD12 { get; set; }
        public double GP_BUD00 { get; set; }
        public double GP_BUD01 { get; set; }
        public double GP_BUD02 { get; set; }
        public double GP_BUD03 { get; set; }
        public double GP_BUD04 { get; set; }
        public double GP_BUD05 { get; set; }
        public double GP_BUD06 { get; set; }
        public double GP_BUD07 { get; set; }
        public double GP_BUD08 { get; set; }
        public double GP_BUD09 { get; set; }
        public double GP_BUD10 { get; set; }
        public double GP_BUD11 { get; set; }
        public double GP_BUD12 { get; set; }
        public double GP_BUDYTD { get; set; }
        public double ACM_GPBUD01 { get; set; }
        public double ACM_GPBUD02 { get; set; }
        public double ACM_GPBUD03 { get; set; }
        public double ACM_GPBUD04 { get; set; }
        public double ACM_GPBUD05 { get; set; }
        public double ACM_GPBUD06 { get; set; }
        public double ACM_GPBUD07 { get; set; }
        public double ACM_GPBUD08 { get; set; }
        public double ACM_GPBUD09 { get; set; }
        public double ACM_GPBUD10 { get; set; }
        public double ACM_GPBUD11 { get; set; }
        public double ACM_GPBUD12 { get; set; }
        public double FC00 { get; set; }
        public double FC01 { get; set; }
        public double FC02 { get; set; }
        public double FC03 { get; set; }
        public double FC04 { get; set; }
        public double FC05 { get; set; }
        public double FC06 { get; set; }
        public double FC07 { get; set; }
        public double FC08 { get; set; }
        public double FC09 { get; set; }
        public double FC10 { get; set; }
        public double FC11 { get; set; }
        public double FC12 { get; set; }
        public double FC_GP00 { get; set; }
        public double FC_GP01 { get; set; }
        public double FC_GP02 { get; set; }
        public double FC_GP03 { get; set; }
        public double FC_GP04 { get; set; }
        public double FC_GP05 { get; set; }
        public double FC_GP06 { get; set; }
        public double FC_GP07 { get; set; }
        public double FC_GP08 { get; set; }
        public double FC_GP09 { get; set; }
        public double FC_GP10 { get; set; }
        public double FC_GP11 { get; set; }
        public double FC_GP12 { get; set; }
        public double FCS00 { get; set; }
        public double FCS01 { get; set; }
        public double FCS02 { get; set; }
        public double FCS03 { get; set; }
        public double FCS04 { get; set; }
        public double FCS05 { get; set; }
        public double FCS06 { get; set; }
        public double FCS07 { get; set; }
        public double FCS08 { get; set; }
        public double FCS09 { get; set; }
        public double FCS10 { get; set; }
        public double FCS11 { get; set; }
        public double FCS12 { get; set; }
        public double ACT00 { get; set; }
        public double ACT01 { get; set; }
        public double ACT02 { get; set; }
        public double ACT03 { get; set; }
        public double ACT04 { get; set; }
        public double ACT05 { get; set; }
        public double ACT06 { get; set; }
        public double ACT07 { get; set; }
        public double ACT08 { get; set; }
        public double ACT09 { get; set; }
        public double ACT10 { get; set; }
        public double ACT11 { get; set; }
        public double ACT12 { get; set; }
        public double ACM_ACT01 { get; set; }
        public double ACM_ACT02 { get; set; }
        public double ACM_ACT03 { get; set; }
        public double ACM_ACT04 { get; set; }
        public double ACM_ACT05 { get; set; }
        public double ACM_ACT06 { get; set; }
        public double ACM_ACT07 { get; set; }
        public double ACM_ACT08 { get; set; }
        public double ACM_ACT09 { get; set; }
        public double ACM_ACT10 { get; set; }
        public double ACM_ACT11 { get; set; }
        public double ACM_ACT12 { get; set; }
        public double GP_ACT00 { get; set; }
        public double GP_ACT01 { get; set; }
        public double GP_ACT02 { get; set; }
        public double GP_ACT03 { get; set; }
        public double GP_ACT04 { get; set; }
        public double GP_ACT05 { get; set; }
        public double GP_ACT06 { get; set; }
        public double GP_ACT07 { get; set; }
        public double GP_ACT08 { get; set; }
        public double GP_ACT09 { get; set; }
        public double GP_ACT10 { get; set; }
        public double GP_ACT11 { get; set; }
        public double GP_ACT12 { get; set; }
        public double ACM_AGP01 { get; set; }
        public double ACM_AGP02 { get; set; }
        public double ACM_AGP03 { get; set; }
        public double ACM_AGP04 { get; set; }
        public double ACM_AGP05 { get; set; }
        public double ACM_AGP06 { get; set; }
        public double ACM_AGP07 { get; set; }
        public double ACM_AGP08 { get; set; }
        public double ACM_AGP09 { get; set; }
        public double ACM_AGP10 { get; set; }
        public double ACM_AGP11 { get; set; }
        public double ACM_AGP12 { get; set; }
        public DateTime AsOf { get; set; }
        public string SECNAM { get; set; }

    }
}
