using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BudgetForecast.Model
{
    public class StoreSearchBudgetPmModel
    {
        public DateTime TIMESTAMP { get; set; }
        public string StYr { get; set; }
        public string CMPSTK { get; set; }
        public string CMP { get; set; }
        public string STKGRP { get; set; }
        public double STKVAL { get; set; }
        public double BUD00 { get; set; }
        public double BUD01 { get; set; }
        public double BUD02 { get; set; }
        public double BUD03 { get; set; }
        public double BUD04 { get; set; }
        public double BUD05 { get; set; }
        public double BUD06 { get; set; }
        public double BUD07 { get; set; }
        public double BUD08 { get; set; }
        public double BUD09 { get; set; }
        public double BUD10 { get; set; }
        public double BUD11 { get; set; }
        public double BUD12 { get; set; }
        public double ACT00 { get; set; }
        public double ACT01 { get; set; }
        public double ACT02 { get; set; }
        public double ACT03 { get; set; }
        public double ACT04 { get; set; }
        public double ACT05 { get; set; }
        public double ACT06 { get; set; }
        public double ACT07 { get; set; }
        public double ACT08 { get; set; }
        public double ACT09 { get; set; }
        public double ACT10 { get; set; }
        public double ACT11 { get; set; }
        public double ACT12 { get; set; }
        public double ATTN00 { get; set; }
        public double ATTN01 { get; set; }
        public double ATTN02 { get; set; }
        public double ATTN03 { get; set; }
        public double ATTN04 { get; set; }
        public double ATTN05 { get; set; }
        public double ATTN06 { get; set; }
        public double ATTN07 { get; set; }
        public double ATTN08 { get; set; }
        public double ATTN09 { get; set; }
        public double ATTN10 { get; set; }
        public double ATTN11 { get; set; }
        public double ATTN12 { get; set; }
        public int TARGET_CUS { get; set; }
        public double NO00 { get; set; }
        public double NO01 { get; set; }
        public double NO02 { get; set; }
        public double NO03 { get; set; }
        public double NO04 { get; set; }
        public double NO05 { get; set; }
        public double NO06 { get; set; }
        public double NO07 { get; set; }
        public double NO08 { get; set; }
        public double NO09 { get; set; }
        public double NO10 { get; set; }
        public double NO11 { get; set; }
        public double NO12 { get; set; }
        public double LASTYR { get; set; }
        public double LNO { get; set; }
        public double LGP00 { get; set; }
        public double THISYR { get; set; }
        public double NO { get; set; }
        public double GP00 { get; set; }
        public double GP01 { get; set; }
        public double GP02 { get; set; }
        public double GP03 { get; set; }
        public double GP04 { get; set; }
        public double GP05 { get; set; }
        public double GP06 { get; set; }
        public double GP07 { get; set; }
        public double GP08 { get; set; }
        public double GP09 { get; set; }
        public double GP10 { get; set; }
        public double GP11 { get; set; }
        public double GP12 { get; set; }
        public double AGP00 { get; set; }
        public double AGP01 { get; set; }
        public double AGP02 { get; set; }
        public double AGP03 { get; set; }
        public double AGP04 { get; set; }
        public double AGP05 { get; set; }
        public double AGP06 { get; set; }
        public double AGP07 { get; set; }
        public double AGP08 { get; set; }
        public double AGP09 { get; set; }
        public double AGP10 { get; set; }
        public double AGP11 { get; set; }
        public double AGP12 { get; set; }
        public DateTime AsOf { get; set; }
        public string StYr_Cy { get; set; }
        public double ACT00_Cy { get; set; }
        public double ACT01_Cy { get; set; }
        public double ACT02_Cy { get; set; }
        public double ACT03_Cy { get; set; }
        public double ACT04_Cy { get; set; }
        public double ACT05_Cy { get; set; }
        public double ACT06_Cy { get; set; }
        public double ACT07_Cy { get; set; }
        public double ACT08_Cy { get; set; }
        public double ACT09_Cy { get; set; }
        public double ACT10_Cy { get; set; }
        public double ACT11_Cy { get; set; }
        public double ACT12_Cy { get; set; }
        public double AGP00_Cy { get; set; }
        public double AGP01_Cy { get; set; }
        public double AGP02_Cy { get; set; }
        public double AGP03_Cy { get; set; }
        public double AGP04_Cy { get; set; }
        public double AGP05_Cy { get; set; }
        public double AGP06_Cy { get; set; }
        public double AGP07_Cy { get; set; }
        public double AGP08_Cy { get; set; }
        public double AGP09_Cy { get; set; }
        public double AGP10_Cy { get; set; }
        public double AGP11_Cy { get; set; }
        public double AGP12_Cy { get; set; }
        public double AGPP_Cy { get; set; }
        public double Cus00_Cy { get; set; }
        public double Cus01_Cy { get; set; }
        public double Cus02_Cy { get; set; }
        public double Cus03_Cy { get; set; }
        public double Cus04_Cy { get; set; }
        public double Cus05_Cy { get; set; }
        public double Cus06_Cy { get; set; }
        public double Cus07_Cy { get; set; }
        public double Cus08_Cy { get; set; }
        public double Cus09_Cy { get; set; }
        public double Cus10_Cy { get; set; }
        public double Cus11_Cy { get; set; }
        public double Cus12_Cy { get; set; }
        public string GRPNAM { get; set; }
        public string SEC { get; set; }
        public string SUBPROD { get; set; }
        public string SECNAM { get; set; }
        public string PROD { get; set; }
        public string PM { get; set; }
        public string NoOfDay { get; set; }
        public string CurMo { get; set; }
        public string TIT000 { get; set; }
        public DateTime AsOfSales { get; set; }
        public double BUDSLM { get; set; }
        public double BUDSLM_Nxt { get; set; }

    }
}
